name: Matthew Sartwell
permalink: /blog/:title
markdown: kramdown
paginate: 3

collections:
    projects:
        output: true
        permalink: /projects/:path/
        imag: "http://i.imgur.com/cqbK361.jpg"

